export { default as Alert } from '@vtex/styleguide/lib/Alert'
export { default as Button } from '@vtex/styleguide/lib/Button'
export { default as Modal } from '@vtex/styleguide/lib/Modal'
export { default as Layout } from '@vtex/styleguide/lib/Layout'
export { default as PageBlock } from '@vtex/styleguide/lib/PageBlock'
export { default as IconInfo } from '@vtex/styleguide/lib/icon/Info'
export { default as Tooltip } from '@vtex/styleguide/lib/Tooltip'
export { default as Dropdwon } from '@vtex/styleguide/lib/Dropdown'
