declare module '@vtex/styleguide/lib/Alert'
declare module '@vtex/styleguide/lib/Button'
declare module '@vtex/styleguide/lib/Modal'
declare module '@vtex/styleguide/lib/Layout'
declare module '@vtex/styleguide/lib/PageBlock'
declare module '@vtex/styleguide/lib/icon/Info'
declare module '@vtex/styleguide/lib/Tooltip'
declare module '@vtex/styleguide/lib/Dropdown'
